# Generated by Django 3.2.5 on 2021-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bid_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descroption', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('image', models.BinaryField()),
            ],
        ),
    ]
