# Generated by Django 3.2.5 on 2021-09-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('startBid', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('Select', models.IntegerField()),
            ],
        ),
    ]
